name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          # Generate changelog
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" HEAD)
          else
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" ${PREV_TAG}..HEAD)
          fi

          # Save to output
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in ${{ github.ref_name }}

            ${{ steps.changelog.outputs.changelog }}

            ## Docker Images

            Pull the Docker image:
            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:latest
            ```

            ## Installation

            See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for installation instructions.
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Release ${{ github.ref_name }} created successfully!"
          echo "📦 Docker images published to GHCR"
